-- ------------------------------------
-- measures.dax
--
-- Basis-Measures fuer das Power-BI-Desktop-Modell
-- auf den MARTS-Tabellen.
-- ------------------------------------

-- Tabelle: mart_player_leaderboard
[Players] =
DISTINCTCOUNT(mart_player_leaderboard[player_uid])

[Avg Expected Points] =
AVERAGE(mart_player_leaderboard[expected_points_next_matchday])

[Avg Start Probability] =
AVERAGE(mart_player_leaderboard[start_probability])

[Avg Value Score] =
AVERAGE(mart_player_leaderboard[value_score])

[Total Market Value] =
SUM(mart_player_leaderboard[market_value])

[Avg Expected MV Delta 7d] =
AVERAGE(mart_player_leaderboard[expected_marketvalue_change_7d])

-- Tabelle: mart_points_breakdown
[Total Predicted Points] =
SUM(mart_points_breakdown[pred_total])

[Total Base EV] =
SUM(mart_points_breakdown[base_raw_ev])

[Total Scorer EV] =
SUM(mart_points_breakdown[scorer_ev])

[Total Win EV] =
SUM(mart_points_breakdown[win_ev])

[Total Minutes EV] =
SUM(mart_points_breakdown[minutes_bonus_ev])

[Total Cards EV] =
SUM(mart_points_breakdown[cards_negative_ev])

-- Tabelle: mart_risk_overview
[Avg P_DNP] =
AVERAGE(mart_risk_overview[p_dnp])

[Avg StdDev Points] =
AVERAGE(mart_risk_overview[stddev_points])

[Avg P90 Minus P10] =
AVERAGEX(
    mart_risk_overview,
    mart_risk_overview[p90_points] - mart_risk_overview[p10_points]
)

