-- ------------------------------------
-- measures.dax
--
-- Basis-Measures fuer das Power-BI-Desktop-Modell
-- auf den MARTS-Tabellen.
-- ------------------------------------

-- Tabelle: mart_player_leaderboard
[Players] =
DISTINCTCOUNT(mart_player_leaderboard[player_uid])

[Avg Expected Points] =
AVERAGE(mart_player_leaderboard[expected_points_next_matchday])

[Avg Start Probability] =
AVERAGE(mart_player_leaderboard[start_probability])

[Avg Value Score] =
AVERAGE(mart_player_leaderboard[value_score])

[Total Market Value] =
SUM(mart_player_leaderboard[market_value])

[Avg Expected MV Delta 7d] =
AVERAGE(mart_player_leaderboard[expected_marketvalue_change_7d])

-- Tabelle: mart_points_breakdown
[Total Predicted Points] =
SUM(mart_points_breakdown[pred_total])

[Total Base EV] =
SUM(mart_points_breakdown[base_raw_ev])

[Total Scorer EV] =
SUM(mart_points_breakdown[scorer_ev])

[Total Win EV] =
SUM(mart_points_breakdown[win_ev])

[Total Minutes EV] =
SUM(mart_points_breakdown[minutes_bonus_ev])

[Total Cards EV] =
SUM(mart_points_breakdown[cards_negative_ev])

-- Tabelle: mart_risk_overview
[Avg P_DNP] =
AVERAGE(mart_risk_overview[p_dnp])

[Avg StdDev Points] =
AVERAGE(mart_risk_overview[stddev_points])

[Avg P90 Minus P10] =
AVERAGEX(
    mart_risk_overview,
    mart_risk_overview[p90_points] - mart_risk_overview[p10_points]
)

-- Tabelle: mart_ml_player_predictions
[ML Players] =
DISTINCTCOUNT(mart_ml_player_predictions[player_uid])

[ML Avg Expected Points Next] =
AVERAGE(mart_ml_player_predictions[expected_points_next_match])

[ML Avg Start Probability] =
AVERAGE(mart_ml_player_predictions[start_probability])

[ML Avg Sub Probability] =
AVERAGE(mart_ml_player_predictions[sub_probability])

[ML Avg Expected Minutes] =
AVERAGE(mart_ml_player_predictions[expected_minutes])

[ML Avg Raw Points Next] =
AVERAGE(mart_ml_player_predictions[expected_raw_points_next_match])

[ML Avg OnTop Points Next] =
AVERAGE(mart_ml_player_predictions[expected_on_top_points_next_match])

-- Tabelle: mart_ml_model_monitoring
[ML Latest Run TS] =
MAX(mart_ml_model_monitoring[ml_run_ts])

[ML Latest RMSE Champion] =
VAR latestRun = MAX(mart_ml_model_monitoring[ml_run_ts])
RETURN
MAXX(
    FILTER(mart_ml_model_monitoring, mart_ml_model_monitoring[ml_run_ts] = latestRun),
    IF(
        mart_ml_model_monitoring[champion_model] = "torch",
        mart_ml_model_monitoring[torch_points_total_rmse],
        mart_ml_model_monitoring[sklearn_points_total_rmse]
    )
)

-- Tabelle: mart_hist_player_profile
[Hist Players] =
DISTINCTCOUNT(mart_hist_player_profile[player_uid])

[Hist Avg Age] =
AVERAGE(mart_hist_player_profile[player_age_years])

[Hist Total Current Market Value] =
SUM(mart_hist_player_profile[current_market_value])

-- Tabelle: mart_hist_player_comparison
[Hist Avg Last 5 Points] =
AVERAGE(mart_hist_player_comparison[avg_points_last_5])

[Hist Avg Last 10 Points] =
AVERAGE(mart_hist_player_comparison[avg_points_last_10])

-- Tabelle: mart_hist_player_marketvalue_curve
[Hist Marketvalue Data Points] =
COUNTROWS(mart_hist_player_marketvalue_curve)

-- Tabelle: mart_hist_team_outlook
[Hist Teams With Outlook] =
DISTINCTCOUNT(mart_hist_team_outlook[team_uid])

[Hist Avg Team Win Probability] =
AVERAGE(mart_hist_team_outlook[team_win_implied_prob])
